variables:
  CIBW_BUILD: cp36-* cp37-*

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps: 
    - task: UsePythonVersion@0
    - bash: |
        set -ex
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
        export PATH="$HOME/.cargo/bin:$PATH"
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.12.0 setuptools setuptools-rust
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.13'}
  steps: 
    - task: UsePythonVersion@0
    - bash: |
        set -ex
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
        export PATH="$HOME/.cargo/bin:$PATH"
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.12.0 setuptools setuptools-rust
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}