trigger:
  branches:
    include:
      - refs/tags/*

variables:
  CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
  CIBW_SKIP: "*_i686"
  CIBW_BEFORE_BUILD: "curl https://sh.rustup.rs -sSf | sh -s -- --profile=minimal -y ; pip install -U setuptools setuptools-rust"
  CIBW_ENVIRONMENT: PATH="$HOME/.cargo/bin:$PATH"

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-20.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.10.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.15'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.10.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
